version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      HOSTNAME_COMMAND: "ifconfig eth0 | grep 'inet addr' | awk '{ print $$2}' | awk -F: '{print $$2}''"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  apiserver:
    image: sentel/apiserver
    user: 777:777
    ports:
      - "4145:4145"
      - "4146:4146"
    links:
      - mongo
      - kafka

  mns:
    image: sentel/mns
    ports:
      - "50061:50061"
    links:
      - mongo
      - kafka

  whaler:
    image: sentel/whaler
    ports:
      - "50060:50060"
    depends_on:
      - mongo
      - kafka
    command: ["/sentel/bin/wait-for-it.sh", "kafka:9092", "--", "/sentel/bin/whaler"]

  broker:
    image: sentel/broker
    ports:
      - "1883:1883"
    depends_on:
        - mongo
        - kafka
    command: ["/sentel/bin/wait-for-it.sh", "kafka:9092", "--", "/sentel/bin/broker",  "-d", "-t", "ssddn", "-P", "tcp", "-l", "0.0.0.0:1883"]