version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      HOSTNAME_COMMAND: "ifconfig eth0 | grep 'inet addr' | awk '{ print $$2}' | awk -F: '{print $$2}''"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#  elasticsearch:
#    image: elasticsearch 
#    ports:
#      - "9200:9200"
#     - "9300:9300"
  apiserver:
    image: sentel/apiserver
    user: 777:777
    ports:
      - "4145:4145"
      - "4146:4146"
    depends_on:
        - mongo
        - kafka
    links:
        - mongo:mongo
        - kafka:kafka
  iotmanager:
    image: sentel/iotmanager
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - zookeeper
      - mongo
      - kafka
    links:
      - mongo:mongo
      - kafka:kafka
      - zookeeper:zookeeper
    command: ["/sentel/bin/wait-for-it.sh", "kafka:9092", "--", "/sentel/bin/iotmanager"]
  mns:
    image: sentel/mns
    ports:
      - "50061:50061"
    depends_on:
      - mongo
      - kafka
    links:
        - mongo:mongo
        - kafka:kafka
  whaler:
    image: sentel/whaler
    ports:
      - "50060:50060"
    depends_on:
      - mongo
      - kafka
    links:
        - mongo:mongo
        - kafka:kafka
    command: ["/sentel/bin/wait-for-it.sh", "kafka:9092", "--", "/sentel/bin/whaler"]
