// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	VersionRequest
	VersionReply
	BrokerRequest
	BrokerReply
	ClientsRequest
	ClientsReply
	Client
	AdminsRequest
	AdminsReply
	ClusterRequest
	ClusterReply
	RoutesRequest
	RoutesReply
	Route
	StatusRequest
	StatusReply
	PluginsRequest
	PluginsReply
	ServicesRequest
	ServicesReply
	Service
	SubscriptionsRequest
	SubscriptionsReply
	Subscription
	SessionsRequest
	SessionsReply
	Session
	TopicsRequest
	TopicsReply
	Topic
	ReplyMessageHeader
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Version
type VersionRequest struct {
}

func (m *VersionRequest) Reset()                    { *m = VersionRequest{} }
func (m *VersionRequest) String() string            { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()               {}
func (*VersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type VersionReply struct {
	Version string `protobuf:"bytes,1,opt,name=Version" json:"Version,omitempty"`
}

func (m *VersionReply) Reset()                    { *m = VersionReply{} }
func (m *VersionReply) String() string            { return proto.CompactTextString(m) }
func (*VersionReply) ProtoMessage()               {}
func (*VersionReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *VersionReply) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// Broker
type BrokerRequest struct {
	Category string `protobuf:"bytes,1,opt,name=Category" json:"Category,omitempty"`
	Service  string `protobuf:"bytes,2,opt,name=Service" json:"Service,omitempty"`
}

func (m *BrokerRequest) Reset()                    { *m = BrokerRequest{} }
func (m *BrokerRequest) String() string            { return proto.CompactTextString(m) }
func (*BrokerRequest) ProtoMessage()               {}
func (*BrokerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BrokerRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *BrokerRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type BrokerReply struct {
	Header  *ReplyMessageHeader `protobuf:"bytes,1,opt,name=Header" json:"Header,omitempty"`
	Stats   map[string]uint64   `protobuf:"bytes,2,rep,name=Stats" json:"Stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Metrics map[string]uint64   `protobuf:"bytes,3,rep,name=Metrics" json:"Metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *BrokerReply) Reset()                    { *m = BrokerReply{} }
func (m *BrokerReply) String() string            { return proto.CompactTextString(m) }
func (*BrokerReply) ProtoMessage()               {}
func (*BrokerReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BrokerReply) GetHeader() *ReplyMessageHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *BrokerReply) GetStats() map[string]uint64 {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *BrokerReply) GetMetrics() map[string]uint64 {
	if m != nil {
		return m.Metrics
	}
	return nil
}

// Clients
type ClientsRequest struct {
	Category string `protobuf:"bytes,1,opt,name=Category" json:"Category,omitempty"`
	Service  string `protobuf:"bytes,2,opt,name=Service" json:"Service,omitempty"`
	ClientId string `protobuf:"bytes,3,opt,name=ClientId" json:"ClientId,omitempty"`
}

func (m *ClientsRequest) Reset()                    { *m = ClientsRequest{} }
func (m *ClientsRequest) String() string            { return proto.CompactTextString(m) }
func (*ClientsRequest) ProtoMessage()               {}
func (*ClientsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ClientsRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *ClientsRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ClientsRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type ClientsReply struct {
	Header  *ReplyMessageHeader `protobuf:"bytes,1,opt,name=Header" json:"Header,omitempty"`
	Clients []*Client           `protobuf:"bytes,2,rep,name=Clients" json:"Clients,omitempty"`
}

func (m *ClientsReply) Reset()                    { *m = ClientsReply{} }
func (m *ClientsReply) String() string            { return proto.CompactTextString(m) }
func (*ClientsReply) ProtoMessage()               {}
func (*ClientsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ClientsReply) GetHeader() *ReplyMessageHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ClientsReply) GetClients() []*Client {
	if m != nil {
		return m.Clients
	}
	return nil
}

type Client struct {
	UserName     string `protobuf:"bytes,1,opt,name=UserName" json:"UserName,omitempty"`
	CleanSession bool   `protobuf:"varint,2,opt,name=CleanSession" json:"CleanSession,omitempty"`
	PeerName     string `protobuf:"bytes,3,opt,name=PeerName" json:"PeerName,omitempty"`
	ConnectTime  string `protobuf:"bytes,4,opt,name=ConnectTime" json:"ConnectTime,omitempty"`
}

func (m *Client) Reset()                    { *m = Client{} }
func (m *Client) String() string            { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()               {}
func (*Client) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Client) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Client) GetCleanSession() bool {
	if m != nil {
		return m.CleanSession
	}
	return false
}

func (m *Client) GetPeerName() string {
	if m != nil {
		return m.PeerName
	}
	return ""
}

func (m *Client) GetConnectTime() string {
	if m != nil {
		return m.ConnectTime
	}
	return ""
}

type AdminsRequest struct {
}

func (m *AdminsRequest) Reset()                    { *m = AdminsRequest{} }
func (m *AdminsRequest) String() string            { return proto.CompactTextString(m) }
func (*AdminsRequest) ProtoMessage()               {}
func (*AdminsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type AdminsReply struct {
}

func (m *AdminsReply) Reset()                    { *m = AdminsReply{} }
func (m *AdminsReply) String() string            { return proto.CompactTextString(m) }
func (*AdminsReply) ProtoMessage()               {}
func (*AdminsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type ClusterRequest struct {
}

func (m *ClusterRequest) Reset()                    { *m = ClusterRequest{} }
func (m *ClusterRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterRequest) ProtoMessage()               {}
func (*ClusterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type ClusterReply struct {
}

func (m *ClusterReply) Reset()                    { *m = ClusterReply{} }
func (m *ClusterReply) String() string            { return proto.CompactTextString(m) }
func (*ClusterReply) ProtoMessage()               {}
func (*ClusterReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

// Routes
type RoutesRequest struct {
	Category string `protobuf:"bytes,1,opt,name=Category" json:"Category,omitempty"`
	Service  string `protobuf:"bytes,2,opt,name=Service" json:"Service,omitempty"`
	Topic    string `protobuf:"bytes,3,opt,name=Topic" json:"Topic,omitempty"`
}

func (m *RoutesRequest) Reset()                    { *m = RoutesRequest{} }
func (m *RoutesRequest) String() string            { return proto.CompactTextString(m) }
func (*RoutesRequest) ProtoMessage()               {}
func (*RoutesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *RoutesRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *RoutesRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *RoutesRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type RoutesReply struct {
	Header *ReplyMessageHeader `protobuf:"bytes,1,opt,name=Header" json:"Header,omitempty"`
	Routes []*Route            `protobuf:"bytes,2,rep,name=Routes" json:"Routes,omitempty"`
}

func (m *RoutesReply) Reset()                    { *m = RoutesReply{} }
func (m *RoutesReply) String() string            { return proto.CompactTextString(m) }
func (*RoutesReply) ProtoMessage()               {}
func (*RoutesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *RoutesReply) GetHeader() *ReplyMessageHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RoutesReply) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type Route struct {
	Topic string   `protobuf:"bytes,1,opt,name=Topic" json:"Topic,omitempty"`
	Route []string `protobuf:"bytes,2,rep,name=Route" json:"Route,omitempty"`
}

func (m *Route) Reset()                    { *m = Route{} }
func (m *Route) String() string            { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()               {}
func (*Route) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Route) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Route) GetRoute() []string {
	if m != nil {
		return m.Route
	}
	return nil
}

// Status
type StatusRequest struct {
}

func (m *StatusRequest) Reset()                    { *m = StatusRequest{} }
func (m *StatusRequest) String() string            { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()               {}
func (*StatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type StatusReply struct {
	Header *ReplyMessageHeader `protobuf:"bytes,1,opt,name=Header" json:"Header,omitempty"`
}

func (m *StatusReply) Reset()                    { *m = StatusReply{} }
func (m *StatusReply) String() string            { return proto.CompactTextString(m) }
func (*StatusReply) ProtoMessage()               {}
func (*StatusReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *StatusReply) GetHeader() *ReplyMessageHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type PluginsRequest struct {
}

func (m *PluginsRequest) Reset()                    { *m = PluginsRequest{} }
func (m *PluginsRequest) String() string            { return proto.CompactTextString(m) }
func (*PluginsRequest) ProtoMessage()               {}
func (*PluginsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type PluginsReply struct {
}

func (m *PluginsReply) Reset()                    { *m = PluginsReply{} }
func (m *PluginsReply) String() string            { return proto.CompactTextString(m) }
func (*PluginsReply) ProtoMessage()               {}
func (*PluginsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

// Service
type ServicesRequest struct {
	Category    string `protobuf:"bytes,1,opt,name=Category" json:"Category,omitempty"`
	ServiceName string `protobuf:"bytes,2,opt,name=ServiceName" json:"ServiceName,omitempty"`
	Listen      string `protobuf:"bytes,3,opt,name=Listen" json:"Listen,omitempty"`
}

func (m *ServicesRequest) Reset()                    { *m = ServicesRequest{} }
func (m *ServicesRequest) String() string            { return proto.CompactTextString(m) }
func (*ServicesRequest) ProtoMessage()               {}
func (*ServicesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ServicesRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *ServicesRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ServicesRequest) GetListen() string {
	if m != nil {
		return m.Listen
	}
	return ""
}

type ServicesReply struct {
	Header   *ReplyMessageHeader `protobuf:"bytes,1,opt,name=Header" json:"Header,omitempty"`
	Services []*Service          `protobuf:"bytes,2,rep,name=Services" json:"Services,omitempty"`
}

func (m *ServicesReply) Reset()                    { *m = ServicesReply{} }
func (m *ServicesReply) String() string            { return proto.CompactTextString(m) }
func (*ServicesReply) ProtoMessage()               {}
func (*ServicesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *ServicesReply) GetHeader() *ReplyMessageHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ServicesReply) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type Service struct {
	ServiceName    string `protobuf:"bytes,1,opt,name=ServiceName" json:"ServiceName,omitempty"`
	Listen         string `protobuf:"bytes,2,opt,name=Listen" json:"Listen,omitempty"`
	Acceptors      uint64 `protobuf:"varint,3,opt,name=Acceptors" json:"Acceptors,omitempty"`
	MaxClients     uint64 `protobuf:"varint,4,opt,name=MaxClients" json:"MaxClients,omitempty"`
	CurrentClients uint64 `protobuf:"varint,5,opt,name=CurrentClients" json:"CurrentClients,omitempty"`
	ShutdownCount  uint64 `protobuf:"varint,6,opt,name=ShutdownCount" json:"ShutdownCount,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *Service) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Service) GetListen() string {
	if m != nil {
		return m.Listen
	}
	return ""
}

func (m *Service) GetAcceptors() uint64 {
	if m != nil {
		return m.Acceptors
	}
	return 0
}

func (m *Service) GetMaxClients() uint64 {
	if m != nil {
		return m.MaxClients
	}
	return 0
}

func (m *Service) GetCurrentClients() uint64 {
	if m != nil {
		return m.CurrentClients
	}
	return 0
}

func (m *Service) GetShutdownCount() uint64 {
	if m != nil {
		return m.ShutdownCount
	}
	return 0
}

// Subscription
type SubscriptionsRequest struct {
	Service      string `protobuf:"bytes,1,opt,name=Service" json:"Service,omitempty"`
	Category     string `protobuf:"bytes,2,opt,name=Category" json:"Category,omitempty"`
	Subscription string `protobuf:"bytes,3,opt,name=Subscription" json:"Subscription,omitempty"`
}

func (m *SubscriptionsRequest) Reset()                    { *m = SubscriptionsRequest{} }
func (m *SubscriptionsRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionsRequest) ProtoMessage()               {}
func (*SubscriptionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *SubscriptionsRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *SubscriptionsRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *SubscriptionsRequest) GetSubscription() string {
	if m != nil {
		return m.Subscription
	}
	return ""
}

type SubscriptionsReply struct {
	Header        *ReplyMessageHeader `protobuf:"bytes,1,opt,name=Header" json:"Header,omitempty"`
	Subscriptions []*Subscription     `protobuf:"bytes,2,rep,name=Subscriptions" json:"Subscriptions,omitempty"`
}

func (m *SubscriptionsReply) Reset()                    { *m = SubscriptionsReply{} }
func (m *SubscriptionsReply) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionsReply) ProtoMessage()               {}
func (*SubscriptionsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *SubscriptionsReply) GetHeader() *ReplyMessageHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SubscriptionsReply) GetSubscriptions() []*Subscription {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

type Subscription struct {
	ClientId  string `protobuf:"bytes,1,opt,name=ClientId" json:"ClientId,omitempty"`
	Topic     string `protobuf:"bytes,2,opt,name=Topic" json:"Topic,omitempty"`
	Attribute string `protobuf:"bytes,3,opt,name=Attribute" json:"Attribute,omitempty"`
}

func (m *Subscription) Reset()                    { *m = Subscription{} }
func (m *Subscription) String() string            { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()               {}
func (*Subscription) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *Subscription) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *Subscription) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Subscription) GetAttribute() string {
	if m != nil {
		return m.Attribute
	}
	return ""
}

// Session
type SessionsRequest struct {
	Category   string          `protobuf:"bytes,1,opt,name=Category" json:"Category,omitempty"`
	Service    string          `protobuf:"bytes,2,opt,name=Service" json:"Service,omitempty"`
	ClientId   string          `protobuf:"bytes,3,opt,name=ClientId" json:"ClientId,omitempty"`
	Conditions map[string]bool `protobuf:"bytes,4,rep,name=Conditions" json:"Conditions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *SessionsRequest) Reset()                    { *m = SessionsRequest{} }
func (m *SessionsRequest) String() string            { return proto.CompactTextString(m) }
func (*SessionsRequest) ProtoMessage()               {}
func (*SessionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *SessionsRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *SessionsRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *SessionsRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *SessionsRequest) GetConditions() map[string]bool {
	if m != nil {
		return m.Conditions
	}
	return nil
}

type SessionsReply struct {
	Header   *ReplyMessageHeader `protobuf:"bytes,1,opt,name=Header" json:"Header,omitempty"`
	Sessions []*Session          `protobuf:"bytes,2,rep,name=Sessions" json:"Sessions,omitempty"`
}

func (m *SessionsReply) Reset()                    { *m = SessionsReply{} }
func (m *SessionsReply) String() string            { return proto.CompactTextString(m) }
func (*SessionsReply) ProtoMessage()               {}
func (*SessionsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *SessionsReply) GetHeader() *ReplyMessageHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SessionsReply) GetSessions() []*Session {
	if m != nil {
		return m.Sessions
	}
	return nil
}

type Session struct {
	ClientId           string `protobuf:"bytes,1,opt,name=ClientId" json:"ClientId,omitempty"`
	CleanSession       bool   `protobuf:"varint,2,opt,name=CleanSession" json:"CleanSession,omitempty"`
	MessageMaxInflight uint64 `protobuf:"varint,3,opt,name=MessageMaxInflight" json:"MessageMaxInflight,omitempty"`
	MessageInflight    uint64 `protobuf:"varint,4,opt,name=MessageInflight" json:"MessageInflight,omitempty"`
	MessageInQueue     uint64 `protobuf:"varint,5,opt,name=MessageInQueue" json:"MessageInQueue,omitempty"`
	MessageDropped     uint64 `protobuf:"varint,6,opt,name=MessageDropped" json:"MessageDropped,omitempty"`
	AwaitingRel        uint64 `protobuf:"varint,7,opt,name=AwaitingRel" json:"AwaitingRel,omitempty"`
	AwaitingComp       uint64 `protobuf:"varint,8,opt,name=AwaitingComp" json:"AwaitingComp,omitempty"`
	AwaitingAck        uint64 `protobuf:"varint,9,opt,name=AwaitingAck" json:"AwaitingAck,omitempty"`
	CreatedAt          string `protobuf:"bytes,10,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *Session) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *Session) GetCleanSession() bool {
	if m != nil {
		return m.CleanSession
	}
	return false
}

func (m *Session) GetMessageMaxInflight() uint64 {
	if m != nil {
		return m.MessageMaxInflight
	}
	return 0
}

func (m *Session) GetMessageInflight() uint64 {
	if m != nil {
		return m.MessageInflight
	}
	return 0
}

func (m *Session) GetMessageInQueue() uint64 {
	if m != nil {
		return m.MessageInQueue
	}
	return 0
}

func (m *Session) GetMessageDropped() uint64 {
	if m != nil {
		return m.MessageDropped
	}
	return 0
}

func (m *Session) GetAwaitingRel() uint64 {
	if m != nil {
		return m.AwaitingRel
	}
	return 0
}

func (m *Session) GetAwaitingComp() uint64 {
	if m != nil {
		return m.AwaitingComp
	}
	return 0
}

func (m *Session) GetAwaitingAck() uint64 {
	if m != nil {
		return m.AwaitingAck
	}
	return 0
}

func (m *Session) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

// Topic
type TopicsRequest struct {
	Service  string `protobuf:"bytes,1,opt,name=Service" json:"Service,omitempty"`
	Category string `protobuf:"bytes,2,opt,name=Category" json:"Category,omitempty"`
	Topic    string `protobuf:"bytes,3,opt,name=Topic" json:"Topic,omitempty"`
}

func (m *TopicsRequest) Reset()                    { *m = TopicsRequest{} }
func (m *TopicsRequest) String() string            { return proto.CompactTextString(m) }
func (*TopicsRequest) ProtoMessage()               {}
func (*TopicsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *TopicsRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *TopicsRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *TopicsRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type TopicsReply struct {
	Header *ReplyMessageHeader `protobuf:"bytes,1,opt,name=Header" json:"Header,omitempty"`
	Topics []*Topic            `protobuf:"bytes,2,rep,name=Topics" json:"Topics,omitempty"`
}

func (m *TopicsReply) Reset()                    { *m = TopicsReply{} }
func (m *TopicsReply) String() string            { return proto.CompactTextString(m) }
func (*TopicsReply) ProtoMessage()               {}
func (*TopicsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *TopicsReply) GetHeader() *ReplyMessageHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *TopicsReply) GetTopics() []*Topic {
	if m != nil {
		return m.Topics
	}
	return nil
}

type Topic struct {
	Topic     string `protobuf:"bytes,1,opt,name=Topic" json:"Topic,omitempty"`
	Attribute string `protobuf:"bytes,2,opt,name=Attribute" json:"Attribute,omitempty"`
}

func (m *Topic) Reset()                    { *m = Topic{} }
func (m *Topic) String() string            { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()               {}
func (*Topic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *Topic) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Topic) GetAttribute() string {
	if m != nil {
		return m.Attribute
	}
	return ""
}

// Message Header
type ReplyMessageHeader struct {
	Success bool   `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	Reason  string `protobuf:"bytes,2,opt,name=Reason" json:"Reason,omitempty"`
}

func (m *ReplyMessageHeader) Reset()                    { *m = ReplyMessageHeader{} }
func (m *ReplyMessageHeader) String() string            { return proto.CompactTextString(m) }
func (*ReplyMessageHeader) ProtoMessage()               {}
func (*ReplyMessageHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *ReplyMessageHeader) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ReplyMessageHeader) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionRequest)(nil), "rpc.VersionRequest")
	proto.RegisterType((*VersionReply)(nil), "rpc.VersionReply")
	proto.RegisterType((*BrokerRequest)(nil), "rpc.BrokerRequest")
	proto.RegisterType((*BrokerReply)(nil), "rpc.BrokerReply")
	proto.RegisterType((*ClientsRequest)(nil), "rpc.ClientsRequest")
	proto.RegisterType((*ClientsReply)(nil), "rpc.ClientsReply")
	proto.RegisterType((*Client)(nil), "rpc.Client")
	proto.RegisterType((*AdminsRequest)(nil), "rpc.AdminsRequest")
	proto.RegisterType((*AdminsReply)(nil), "rpc.AdminsReply")
	proto.RegisterType((*ClusterRequest)(nil), "rpc.ClusterRequest")
	proto.RegisterType((*ClusterReply)(nil), "rpc.ClusterReply")
	proto.RegisterType((*RoutesRequest)(nil), "rpc.RoutesRequest")
	proto.RegisterType((*RoutesReply)(nil), "rpc.RoutesReply")
	proto.RegisterType((*Route)(nil), "rpc.Route")
	proto.RegisterType((*StatusRequest)(nil), "rpc.StatusRequest")
	proto.RegisterType((*StatusReply)(nil), "rpc.StatusReply")
	proto.RegisterType((*PluginsRequest)(nil), "rpc.PluginsRequest")
	proto.RegisterType((*PluginsReply)(nil), "rpc.PluginsReply")
	proto.RegisterType((*ServicesRequest)(nil), "rpc.ServicesRequest")
	proto.RegisterType((*ServicesReply)(nil), "rpc.ServicesReply")
	proto.RegisterType((*Service)(nil), "rpc.Service")
	proto.RegisterType((*SubscriptionsRequest)(nil), "rpc.SubscriptionsRequest")
	proto.RegisterType((*SubscriptionsReply)(nil), "rpc.SubscriptionsReply")
	proto.RegisterType((*Subscription)(nil), "rpc.Subscription")
	proto.RegisterType((*SessionsRequest)(nil), "rpc.SessionsRequest")
	proto.RegisterType((*SessionsReply)(nil), "rpc.SessionsReply")
	proto.RegisterType((*Session)(nil), "rpc.Session")
	proto.RegisterType((*TopicsRequest)(nil), "rpc.TopicsRequest")
	proto.RegisterType((*TopicsReply)(nil), "rpc.TopicsReply")
	proto.RegisterType((*Topic)(nil), "rpc.Topic")
	proto.RegisterType((*ReplyMessageHeader)(nil), "rpc.ReplyMessageHeader")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Api service

type ApiClient interface {
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionReply, error)
	Admins(ctx context.Context, in *AdminsRequest, opts ...grpc.CallOption) (*AdminsReply, error)
	Cluster(ctx context.Context, in *ClusterRequest, opts ...grpc.CallOption) (*ClusterReply, error)
	Routes(ctx context.Context, in *RoutesRequest, opts ...grpc.CallOption) (*RoutesReply, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error)
	Broker(ctx context.Context, in *BrokerRequest, opts ...grpc.CallOption) (*BrokerReply, error)
	Plugins(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*PluginsReply, error)
	Services(ctx context.Context, in *ServicesRequest, opts ...grpc.CallOption) (*ServicesReply, error)
	Subscriptions(ctx context.Context, in *SubscriptionsRequest, opts ...grpc.CallOption) (*SubscriptionsReply, error)
	Clients(ctx context.Context, in *ClientsRequest, opts ...grpc.CallOption) (*ClientsReply, error)
	Sessions(ctx context.Context, in *SessionsRequest, opts ...grpc.CallOption) (*SessionsReply, error)
	Topics(ctx context.Context, in *TopicsRequest, opts ...grpc.CallOption) (*TopicsReply, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionReply, error) {
	out := new(VersionReply)
	err := grpc.Invoke(ctx, "/rpc.Api/Version", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Admins(ctx context.Context, in *AdminsRequest, opts ...grpc.CallOption) (*AdminsReply, error) {
	out := new(AdminsReply)
	err := grpc.Invoke(ctx, "/rpc.Api/Admins", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Cluster(ctx context.Context, in *ClusterRequest, opts ...grpc.CallOption) (*ClusterReply, error) {
	out := new(ClusterReply)
	err := grpc.Invoke(ctx, "/rpc.Api/Cluster", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Routes(ctx context.Context, in *RoutesRequest, opts ...grpc.CallOption) (*RoutesReply, error) {
	out := new(RoutesReply)
	err := grpc.Invoke(ctx, "/rpc.Api/Routes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := grpc.Invoke(ctx, "/rpc.Api/Status", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Broker(ctx context.Context, in *BrokerRequest, opts ...grpc.CallOption) (*BrokerReply, error) {
	out := new(BrokerReply)
	err := grpc.Invoke(ctx, "/rpc.Api/Broker", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Plugins(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*PluginsReply, error) {
	out := new(PluginsReply)
	err := grpc.Invoke(ctx, "/rpc.Api/Plugins", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Services(ctx context.Context, in *ServicesRequest, opts ...grpc.CallOption) (*ServicesReply, error) {
	out := new(ServicesReply)
	err := grpc.Invoke(ctx, "/rpc.Api/Services", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Subscriptions(ctx context.Context, in *SubscriptionsRequest, opts ...grpc.CallOption) (*SubscriptionsReply, error) {
	out := new(SubscriptionsReply)
	err := grpc.Invoke(ctx, "/rpc.Api/Subscriptions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Clients(ctx context.Context, in *ClientsRequest, opts ...grpc.CallOption) (*ClientsReply, error) {
	out := new(ClientsReply)
	err := grpc.Invoke(ctx, "/rpc.Api/Clients", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Sessions(ctx context.Context, in *SessionsRequest, opts ...grpc.CallOption) (*SessionsReply, error) {
	out := new(SessionsReply)
	err := grpc.Invoke(ctx, "/rpc.Api/Sessions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Topics(ctx context.Context, in *TopicsRequest, opts ...grpc.CallOption) (*TopicsReply, error) {
	out := new(TopicsReply)
	err := grpc.Invoke(ctx, "/rpc.Api/Topics", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Api service

type ApiServer interface {
	Version(context.Context, *VersionRequest) (*VersionReply, error)
	Admins(context.Context, *AdminsRequest) (*AdminsReply, error)
	Cluster(context.Context, *ClusterRequest) (*ClusterReply, error)
	Routes(context.Context, *RoutesRequest) (*RoutesReply, error)
	Status(context.Context, *StatusRequest) (*StatusReply, error)
	Broker(context.Context, *BrokerRequest) (*BrokerReply, error)
	Plugins(context.Context, *PluginsRequest) (*PluginsReply, error)
	Services(context.Context, *ServicesRequest) (*ServicesReply, error)
	Subscriptions(context.Context, *SubscriptionsRequest) (*SubscriptionsReply, error)
	Clients(context.Context, *ClientsRequest) (*ClientsReply, error)
	Sessions(context.Context, *SessionsRequest) (*SessionsReply, error)
	Topics(context.Context, *TopicsRequest) (*TopicsReply, error)
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Api/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Admins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Admins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Api/Admins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Admins(ctx, req.(*AdminsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Cluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Cluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Api/Cluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Cluster(ctx, req.(*ClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Routes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Routes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Api/Routes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Routes(ctx, req.(*RoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Api/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Broker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrokerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Broker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Api/Broker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Broker(ctx, req.(*BrokerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Plugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Plugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Api/Plugins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Plugins(ctx, req.(*PluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Services_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Services(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Api/Services",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Services(ctx, req.(*ServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Subscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Subscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Api/Subscriptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Subscriptions(ctx, req.(*SubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Clients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Clients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Api/Clients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Clients(ctx, req.(*ClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Sessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Sessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Api/Sessions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Sessions(ctx, req.(*SessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Topics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Topics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Api/Topics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Topics(ctx, req.(*TopicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Api_Version_Handler,
		},
		{
			MethodName: "Admins",
			Handler:    _Api_Admins_Handler,
		},
		{
			MethodName: "Cluster",
			Handler:    _Api_Cluster_Handler,
		},
		{
			MethodName: "Routes",
			Handler:    _Api_Routes_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Api_Status_Handler,
		},
		{
			MethodName: "Broker",
			Handler:    _Api_Broker_Handler,
		},
		{
			MethodName: "Plugins",
			Handler:    _Api_Plugins_Handler,
		},
		{
			MethodName: "Services",
			Handler:    _Api_Services_Handler,
		},
		{
			MethodName: "Subscriptions",
			Handler:    _Api_Subscriptions_Handler,
		},
		{
			MethodName: "Clients",
			Handler:    _Api_Clients_Handler,
		},
		{
			MethodName: "Sessions",
			Handler:    _Api_Sessions_Handler,
		},
		{
			MethodName: "Topics",
			Handler:    _Api_Topics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x57, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0xcf, 0xd9, 0xb1, 0xe3, 0x8c, 0xed, 0x24, 0xdd, 0x46, 0xf4, 0x30, 0x7f, 0x14, 0xad, 0x0a,
	0xf2, 0x93, 0x81, 0x44, 0xa2, 0x55, 0x11, 0x48, 0xc6, 0x0d, 0xa2, 0x12, 0x41, 0xe5, 0x5c, 0x78,
	0x41, 0x42, 0x3a, 0x9f, 0xb7, 0xee, 0x11, 0xe7, 0xee, 0xd8, 0xdb, 0x6b, 0x9b, 0x17, 0x1e, 0x79,
	0xe0, 0x53, 0xf0, 0x8d, 0xf8, 0x1a, 0x7c, 0x05, 0xde, 0xd0, 0xee, 0xce, 0xee, 0xed, 0x5e, 0x52,
	0x28, 0x8e, 0xfa, 0x76, 0xf3, 0x9b, 0x3f, 0x3b, 0x7f, 0x76, 0x76, 0xe6, 0x60, 0x37, 0x2e, 0xd2,
	0x49, 0xc1, 0x73, 0x91, 0x93, 0x36, 0x2f, 0x12, 0x7a, 0x00, 0x7b, 0x3f, 0x30, 0x5e, 0xa6, 0x79,
	0x16, 0xb1, 0x5f, 0x2a, 0x56, 0x0a, 0x3a, 0x86, 0x81, 0x45, 0x8a, 0xf5, 0x25, 0x09, 0x61, 0x07,
	0xe9, 0x30, 0x38, 0x0a, 0xc6, 0xbb, 0x91, 0x21, 0xe9, 0x29, 0x0c, 0xbf, 0xe4, 0xf9, 0x39, 0xe3,
	0xa8, 0x4a, 0x46, 0xd0, 0x9b, 0xc5, 0x82, 0xad, 0x72, 0x7e, 0x89, 0xb2, 0x96, 0x96, 0x66, 0xe6,
	0x8c, 0x3f, 0x4f, 0x13, 0x16, 0xb6, 0xb4, 0x19, 0x24, 0xe9, 0x1f, 0x2d, 0xe8, 0x1b, 0x3b, 0xf2,
	0xc0, 0x8f, 0xa0, 0xfb, 0x35, 0x8b, 0x97, 0x8c, 0x2b, 0x1b, 0xfd, 0xe3, 0x3b, 0x13, 0x5e, 0x24,
	0x13, 0xc5, 0x3b, 0x63, 0x65, 0x19, 0xaf, 0x98, 0x66, 0x47, 0x28, 0x46, 0x3e, 0x81, 0xce, 0x5c,
	0xc4, 0xa2, 0x0c, 0x5b, 0x47, 0xed, 0x71, 0xff, 0xf8, 0x1d, 0x25, 0xef, 0x58, 0x9c, 0x28, 0xee,
	0x69, 0x26, 0xf8, 0x65, 0xa4, 0x25, 0xc9, 0x3d, 0xd8, 0x39, 0x63, 0x82, 0xa7, 0x49, 0x19, 0xb6,
	0x95, 0xd2, 0x7b, 0x57, 0x94, 0x90, 0xaf, 0xd5, 0x8c, 0xf4, 0xe8, 0x3e, 0x40, 0x6d, 0x8d, 0x1c,
	0x40, 0xfb, 0x9c, 0x99, 0x58, 0xe5, 0x27, 0x39, 0x84, 0xce, 0xf3, 0x78, 0x5d, 0xe9, 0x20, 0xb7,
	0x23, 0x4d, 0x3c, 0x68, 0xdd, 0x0f, 0x46, 0x0f, 0x60, 0xe0, 0x9a, 0xfc, 0x3f, 0xba, 0x74, 0x01,
	0x7b, 0xb3, 0x75, 0xca, 0x32, 0x51, 0xde, 0x28, 0xd5, 0x4a, 0x4b, 0xd9, 0x79, 0xb4, 0x0c, 0xdb,
	0xa8, 0x85, 0x34, 0x7d, 0x0a, 0x03, 0x7b, 0xc6, 0x46, 0x65, 0xf8, 0x00, 0x76, 0xd0, 0x00, 0x16,
	0xa2, 0xaf, 0x34, 0x34, 0x16, 0x19, 0x1e, 0xfd, 0x2d, 0x80, 0xae, 0xfe, 0x96, 0xee, 0x7c, 0x5f,
	0x32, 0xfe, 0x6d, 0x7c, 0xc1, 0x4c, 0x10, 0x86, 0x26, 0x54, 0xba, 0xc3, 0xe2, 0x6c, 0xce, 0x4a,
	0x75, 0xf7, 0x64, 0x24, 0xbd, 0xc8, 0xc3, 0xa4, 0xfe, 0x63, 0x86, 0xfa, 0x18, 0x8e, 0xa1, 0xc9,
	0x11, 0xf4, 0x67, 0x79, 0x96, 0xb1, 0x44, 0x3c, 0x49, 0x2f, 0x58, 0xb8, 0xad, 0xd8, 0x2e, 0x44,
	0xf7, 0x61, 0x38, 0x5d, 0x5e, 0xa4, 0x99, 0xc9, 0x29, 0x1d, 0x42, 0xdf, 0x00, 0xc5, 0xfa, 0x52,
	0xb6, 0xc6, 0x6c, 0x5d, 0x95, 0xc2, 0xde, 0x6f, 0xba, 0x27, 0x7d, 0x42, 0x44, 0x4a, 0xfc, 0x08,
	0xc3, 0x28, 0xaf, 0x04, 0xbb, 0x61, 0x55, 0x0e, 0xa1, 0xf3, 0x24, 0x2f, 0xd2, 0x04, 0x63, 0xd0,
	0x04, 0x5d, 0x40, 0xdf, 0x18, 0xdf, 0xa8, 0x1c, 0x14, 0xba, 0x5a, 0x1f, 0xab, 0x01, 0x5a, 0x41,
	0x42, 0x11, 0x72, 0xe8, 0x09, 0x74, 0xd4, 0x57, 0xed, 0x42, 0xe0, 0xb8, 0x20, 0x51, 0xc5, 0x56,
	0x16, 0x76, 0x23, 0x4d, 0xc8, 0xbc, 0xc9, 0x16, 0xa8, 0x6c, 0xde, 0xbe, 0x80, 0xbe, 0x01, 0x36,
	0xf1, 0x54, 0x26, 0xfa, 0xf1, 0xba, 0x5a, 0x39, 0x95, 0xd8, 0x83, 0x81, 0x45, 0x64, 0xa2, 0x57,
	0xb0, 0x8f, 0xc9, 0x7a, 0xad, 0x54, 0x1f, 0x41, 0x1f, 0xc5, 0xd5, 0xd5, 0xd0, 0xe9, 0x76, 0x21,
	0xf2, 0x16, 0x74, 0xbf, 0x49, 0x4b, 0xc1, 0x32, 0xcc, 0x39, 0x52, 0xf4, 0x67, 0x18, 0xd6, 0x07,
	0x6d, 0x94, 0xf6, 0x31, 0xf4, 0x8c, 0x05, 0x4c, 0xfc, 0x40, 0xa9, 0x20, 0x18, 0x59, 0x2e, 0xfd,
	0x33, 0xb0, 0x37, 0xa2, 0xe9, 0x71, 0xf0, 0x6f, 0x1e, 0xb7, 0x5c, 0x8f, 0xc9, 0xbb, 0xb0, 0x3b,
	0x4d, 0x12, 0x56, 0x88, 0x9c, 0x97, 0x2a, 0x98, 0xed, 0xa8, 0x06, 0xc8, 0xfb, 0x00, 0x67, 0xf1,
	0x4b, 0xd3, 0x96, 0xdb, 0x8a, 0xed, 0x20, 0xe4, 0x43, 0xd8, 0x9b, 0x55, 0x9c, 0xb3, 0x4c, 0x18,
	0x99, 0x8e, 0x92, 0x69, 0xa0, 0xe4, 0x2e, 0x0c, 0xe7, 0xcf, 0x2a, 0xb1, 0xcc, 0x5f, 0x64, 0xb3,
	0xbc, 0xca, 0x44, 0xd8, 0x55, 0x62, 0x3e, 0x48, 0x0b, 0x38, 0x9c, 0x57, 0x8b, 0x32, 0xe1, 0x69,
	0x21, 0xd2, 0xdc, 0x96, 0xd3, 0xbd, 0xfa, 0xc1, 0xd5, 0x07, 0xc9, 0x54, 0xb1, 0xd5, 0xa8, 0x22,
	0x85, 0x81, 0x6b, 0x0d, 0x2b, 0xe5, 0x61, 0xf4, 0x57, 0x20, 0x8d, 0x13, 0x37, 0x2a, 0xda, 0x3d,
	0x18, 0x7a, 0x66, 0xb0, 0x72, 0xb7, 0x74, 0xe5, 0x1c, 0x4e, 0xe4, 0xcb, 0xd1, 0x9f, 0x7c, 0x1f,
	0xbd, 0x07, 0x36, 0xf0, 0x1f, 0xd8, 0xba, 0xc7, 0x5a, 0x6e, 0x8f, 0xc9, 0xfa, 0x09, 0xc1, 0xd3,
	0x85, 0xec, 0x33, 0x1d, 0x62, 0x0d, 0xd0, 0xbf, 0x02, 0x79, 0xf3, 0xd5, 0x6b, 0xf7, 0xe6, 0x9e,
	0x7e, 0xf2, 0x10, 0x60, 0x96, 0x67, 0xcb, 0x54, 0xc7, 0xbe, 0xad, 0x62, 0xbf, 0x8b, 0xb7, 0xd6,
	0x3b, 0x7b, 0x52, 0x8b, 0xe9, 0xb9, 0xe8, 0xe8, 0x8d, 0x3e, 0x87, 0xfd, 0x06, 0xfb, 0xbf, 0x66,
	0x5c, 0xcf, 0x9d, 0x71, 0xaa, 0xf5, 0xcc, 0x69, 0x9b, 0xb7, 0x9e, 0xb6, 0xd0, 0x68, 0x3d, 0x05,
	0x46, 0x96, 0x4b, 0xff, 0x6e, 0xc9, 0x3c, 0xd9, 0x21, 0xf2, 0xca, 0x92, 0xbd, 0xce, 0x10, 0x9a,
	0x00, 0x41, 0x77, 0xce, 0xe2, 0x97, 0x8f, 0xb2, 0xa7, 0xeb, 0x74, 0xf5, 0x4c, 0x60, 0x27, 0x5e,
	0xc3, 0x21, 0x63, 0xd8, 0x47, 0xd4, 0x0a, 0xeb, 0xbe, 0x6c, 0xc2, 0xb2, 0x39, 0x2d, 0xf4, 0x5d,
	0xc5, 0x2a, 0x66, 0x9a, 0xd3, 0x47, 0x1d, 0xb9, 0x87, 0x3c, 0x2f, 0x0a, 0xb6, 0xc4, 0xee, 0x6c,
	0xa0, 0xf2, 0x91, 0x99, 0xbe, 0x88, 0x53, 0x91, 0x66, 0xab, 0x88, 0xad, 0xc3, 0x1d, 0x25, 0xe4,
	0x42, 0x32, 0x5e, 0x43, 0xce, 0xf2, 0x8b, 0x22, 0xec, 0x29, 0x11, 0x0f, 0x73, 0xad, 0x4c, 0x93,
	0xf3, 0x70, 0xd7, 0xb7, 0x32, 0x4d, 0xce, 0xe5, 0x95, 0x9e, 0x71, 0x16, 0x0b, 0xb6, 0x9c, 0x8a,
	0x10, 0xf4, 0x95, 0xb6, 0x80, 0x1c, 0x9a, 0xea, 0xe6, 0xdf, 0xf0, 0x75, 0x78, 0xe5, 0xd0, 0x34,
	0xc6, 0x37, 0x1d, 0x9a, 0x5a, 0xdf, 0x1b, 0x9a, 0x0a, 0x8a, 0x90, 0x43, 0x3f, 0x83, 0x7a, 0x3c,
	0x5e, 0x33, 0x34, 0xbd, 0x86, 0x6e, 0x35, 0x1b, 0xfa, 0x2b, 0x20, 0x57, 0x8f, 0x57, 0x29, 0xa8,
	0x92, 0x84, 0x95, 0xa5, 0xb2, 0xd5, 0x8b, 0x0c, 0x29, 0x9f, 0xfd, 0x88, 0xc5, 0x65, 0x6e, 0x9f,
	0x7d, 0x4d, 0x1d, 0xff, 0xde, 0x81, 0xf6, 0xb4, 0x48, 0xc9, 0x89, 0xdd, 0xce, 0xc9, 0x6d, 0xe5,
	0xab, 0xbf, 0xcd, 0x8f, 0x6e, 0xf9, 0xa0, 0x1c, 0xa6, 0x5b, 0xe4, 0x63, 0xe8, 0xea, 0x45, 0x87,
	0x10, 0xc5, 0xf6, 0xd6, 0xa0, 0xd1, 0x81, 0x87, 0x69, 0x8d, 0x13, 0xb9, 0xdb, 0xa9, 0xcd, 0x07,
	0x8f, 0xf1, 0x37, 0x23, 0x3c, 0xc6, 0x5b, 0x8e, 0xd4, 0x31, 0x7a, 0xcf, 0xc0, 0x63, 0xbc, 0x5d,
	0x09, 0x8f, 0x71, 0x56, 0x1c, 0xad, 0xa1, 0x37, 0x09, 0xd4, 0xf0, 0xf6, 0x0c, 0xd4, 0x70, 0x56,
	0x0d, 0xad, 0xa1, 0x97, 0x76, 0xd4, 0xf0, 0x7e, 0x48, 0x50, 0xc3, 0xd9, 0xea, 0x75, 0x28, 0xb8,
	0x5b, 0x60, 0x28, 0xfe, 0xee, 0x81, 0xa1, 0x78, 0xeb, 0xc7, 0x16, 0xf9, 0xb4, 0x9e, 0xea, 0xe4,
	0xd0, 0x9d, 0xe7, 0x56, 0x8d, 0x34, 0x50, 0xad, 0x77, 0xda, 0x18, 0x2c, 0xe4, 0xed, 0x2b, 0x23,
	0xc5, 0x5a, 0xb8, 0x73, 0x1d, 0xcb, 0x49, 0xbf, 0x9e, 0xc4, 0xb7, 0x9d, 0xa5, 0xba, 0x6c, 0xa6,
	0xbf, 0x5e, 0xdf, 0x8d, 0xcf, 0xfa, 0xc1, 0xb3, 0x3e, 0x7b, 0xaf, 0xb9, 0xf5, 0xd9, 0x79, 0x75,
	0x75, 0x4a, 0xf5, 0x4d, 0xc7, 0x94, 0x7a, 0xdd, 0x8a, 0x29, 0x75, 0x9a, 0x8c, 0x6e, 0x2d, 0xba,
	0xea, 0x87, 0xf2, 0xe4, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcc, 0xe9, 0x9d, 0x97, 0x5d, 0x0e,
	0x00, 0x00,
}
