apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: apiserver-deployment
spec:
  selector:
    matchLabels:
      app: apiserver 
  replicas: 1
  template: 
    metadata:
      labels:
        app: apiserver 
    spec:
      containers:
      - name: apiserver 
        image: sentel/apiserver 
        ports:
        - containerPort: 80

