apiVersion: apps/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: iothub-deployment
spec:
  selector:
    matchLabels:
      app: iothub 
  replicas: 1
  template: 
    metadata:
      labels:
        app: iothub 
    spec:
      containers:
      - name: iothub 
        image: sentel/iothub
        ports:
        - containerPort: 80

