apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: iotmanager-deployment
spec:
  selector:
    matchLabels:
      app: iotmanager 
  replicas: 1
  template: 
    metadata:
      labels:
        app: iotmanager 
    spec:
      containers:
      - name: iotmanager 
        image: sentel/iotmanager 
        ports:
        - containerPort: 8080

