apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mns-deployment
spec:
  selector:
    matchLabels:
      app: mns 
  replicas: 1
  template: 
    metadata:
      labels:
        app: mns 
    spec:
      containers:
      - name: mns 
        image: sentel/mns 
        ports:
        - containerPort: 50060 

