apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: whaler-deployment
spec:
  selector:
    matchLabels:
      app: whaler 
  replicas: 1
  template: 
    metadata:
      labels:
        app: whaler 
    spec:
      containers:
      - name: whaler 
        image: sentel/whaler
        ports:
        - containerPort: 50060 

