apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: zk-deployment
spec:
  selector:
    matchLabels:
      app: apiserver 
  replicas: 1
  template: 
    metadata:
      labels:
        app: apiserver 
    spec:
      containers:
      - name: apiserver 
        image: sentel/apiserver 
        ports:
        - containerPort: 80

